// flow-typed signature: 0e235bf31f5ae208a03af8ec18e2f539
// flow-typed version: <<STUB>>/eslint-config-wesbos_v^0.0.19/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-wesbos'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-wesbos' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'eslint-config-wesbos/index' {
  declare module.exports: $Exports<'eslint-config-wesbos'>;
}
declare module 'eslint-config-wesbos/index.js' {
  declare module.exports: $Exports<'eslint-config-wesbos'>;
}
