// flow-typed signature: 5e39ae481932b62f7cde24b32027ce89
// flow-typed version: <<STUB>>/react-switch_v^5.0.1/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-switch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-switch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-switch/dist/react-switch.dev' {
  declare module.exports: any;
}

declare module 'react-switch/dist/react-switch.min' {
  declare module.exports: any;
}

declare module 'react-switch/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-switch/dist/react-switch.dev.js' {
  declare module.exports: $Exports<'react-switch/dist/react-switch.dev'>;
}
declare module 'react-switch/dist/react-switch.min.js' {
  declare module.exports: $Exports<'react-switch/dist/react-switch.min'>;
}
declare module 'react-switch/index' {
  declare module.exports: $Exports<'react-switch'>;
}
declare module 'react-switch/index.js' {
  declare module.exports: $Exports<'react-switch'>;
}
declare module 'react-switch/rollup.config.js' {
  declare module.exports: $Exports<'react-switch/rollup.config'>;
}
